# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy project files
COPY package.json pnpm-lock.yaml tsconfig.json tsup.config.ts .
COPY src ./src

# Install dependencies and build
RUN pnpm install && pnpm run build

# Default command
CMD ["node","dist/index.js"]
